### ISSUE TITLE
processing sample.warc.gz infinite loop

### ISSUE THREAD

**Issue by bogrol2003** [StractOrg/stract#241]
What versions of rust exactly are you using? Both the latest and a month old commit are getting into a loop with just configure.

```
Finished `release` profile [optimized + debuginfo] target(s) in 0.93s
     Running `target/release/stract configure`
warning: some trace filter directives would enable traces that are disabled statically
note: `none=trace` would enable the TRACE level for the `none` target
note: the static max level is `info`
help: to enable DEBUG logging, remove the `max_level_info` feature from the `tracing` crate
 INFO Skipping sample.warc.gz
 INFO Skipping bangs.json
 INFO Skipping english-wordnet-2022-subset.ttl
 INFO Skipping lambdamart.txt
 INFO Skipping test.zim
 INFO Skipping internet_archive.warc.gz
 INFO processing sample.warc.gz
 INFO sample.warc.gz done
 INFO processing sample.warc.gz
 INFO sample.warc.gz done
 INFO processing sample.warc.gz
```

Also, this error appears when just dev is running, preventing the search from working.

```
thread 'main' panicked at /home/bogrol/stract/crates/core/src/searcher/api/mod.rs:288:74:
called `Result::unwrap()` on an `Err` value: CheckerNotFound
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1104:23
   4: stract::searcher::api::ApiSearcher<S,L,G>::new::{{closure}}
             at ./crates/core/src/searcher/api/mod.rs:288:26
   5: core::option::Option<T>::map
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/option.rs:1113:29
   6: stract::searcher::api::ApiSearcher<S,L,G>::new
             at ./crates/core/src/searcher/api/mod.rs:286:28
   7: stract::api::router::{{closure}}
             at ./crates/core/src/api/mod.rs:212:13
   8: stract::entrypoint::api::run::{{closure}}
             at ./crates/core/src/entrypoint/api.rs:178:58
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/future/future.rs:123:9
  10: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/bogrol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.0/src/runtime/park.rs:281:63
  11: tokio::runtime::coop::with_budget
             at /home/bogrol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.0/src/runtime/coop.rs:107:5
  12: tokio::runtime::coop::budget
             at /home/bogrol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.0/src/runtime/coop.rs:73:5
  13: tokio::runtime::park::CachedParkThread::block_on
             at /home/bogrol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.0/src/runtime/park.rs:281:31
  14: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/bogrol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.0/src/runtime/context/blocking.rs:66:9
  15: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/bogrol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  16: tokio::runtime::context::runtime::enter_runtime
             at /home/bogrol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.0/src/runtime/context/runtime.rs:65:16
  17: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/bogrol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  18: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/bogrol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.0/src/runtime/runtime.rs:370:45
  19: tokio::runtime::runtime::Runtime::block_on
             at /home/bogrol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.0/src/runtime/runtime.rs:340:13
  20: stract::main
             at ./crates/core/src/main.rs:370:13
  21: core::ops::function::FnOnce::call_once
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Finished running. Exit status: 101]
```

**Comment by mikkeldenker** [comment]
I'm currently using `v1.84.0-beta.1` locally.
Just configure does not go into an infinite loop, it's just processing the same file multiple times for different purposes (web graph, search index, spell checker etc). Admittedly the logs should indicate this better.

I think the error you're experiencing might be happening if `just dev` is run before the spell checker was finished building during `just configure`.

Closing this as I don't think there is a bug.
